spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: iamAshu@job1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  thymeleaf:
    cache: false
    debug: true

logging:
  level:
    org.springframework.security: DEBUG
    com.jwt.example: DEBUG
    root: INFO

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

server:
  port: 8081
# Okta configuration for API gateway
okta:
  oauth2:
    issuer: https://dev-26937441.okta.com/oauth2/default
    audience: api://default