spring:
  application:
    name: APIGATEWAY

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**, /staffs/**
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**

server:
  port: 8084

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    prefer-ip-address: true

# Okta configuration for API gateway
okta:
  oauth2:
    issuer: https://dev-26937441.okta.com/oauth2/default
    audience: api://default
    client-id: 0oamnjem22Hx3IMFD5d7
    client-secret: cDtquFc8AdriHOsGhzj4-JAWJcKddaOUE3CnDGKXVYj_cGLeZO5MckPARSmoKI0L
    scopes: openid, profile, email, offline_access
